### ISSUE TITLE
License on nginx_log_by_lua

### ISSUE THREAD

**Issue by alexfernandez** [mtourne/nginx_log_by_lua#2]
Hi, I cannot find the license on the project code. I suppose it is open source since it's published here on GitHub, but I would like to publish it (with modifications) for an upcoming blog post. Can you clarify what it is? Thanks!

**Comment by mtourne** [comment]
Added License, picked Apache 2.0. Similar to BSD/MIT with some extra legal niceties.

**Comment by alexfernandez** [comment]
Thanks!
